// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/rep/service.proto

/*
Package rep is a generated protocol buffer package.

It is generated from these files:
	rpc/rep/service.proto

It has these top-level messages:
	VoteReq
	VoteResp
	VotesReq
	VotesResp
	VoteRecord
*/
package rep

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import ericmoritz_users_users "github.com/ericmoritz/twirp-users/rpc/users"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type VoteReq struct {
	// This request requries a valid users.Session
	Session *ericmoritz_users_users.Session `protobuf:"bytes,1,opt,name=session" json:"session,omitempty"`
	Target  string                          `protobuf:"bytes,3,opt,name=target" json:"target,omitempty"`
}

func (m *VoteReq) Reset()                    { *m = VoteReq{} }
func (m *VoteReq) String() string            { return proto.CompactTextString(m) }
func (*VoteReq) ProtoMessage()               {}
func (*VoteReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *VoteReq) GetSession() *ericmoritz_users_users.Session {
	if m != nil {
		return m.Session
	}
	return nil
}

func (m *VoteReq) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

type VoteResp struct {
}

func (m *VoteResp) Reset()                    { *m = VoteResp{} }
func (m *VoteResp) String() string            { return proto.CompactTextString(m) }
func (*VoteResp) ProtoMessage()               {}
func (*VoteResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type VotesReq struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
}

func (m *VotesReq) Reset()                    { *m = VotesReq{} }
func (m *VotesReq) String() string            { return proto.CompactTextString(m) }
func (*VotesReq) ProtoMessage()               {}
func (*VotesReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *VotesReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type VotesResp struct {
	Count uint64 `protobuf:"varint,1,opt,name=count" json:"count,omitempty"`
}

func (m *VotesResp) Reset()                    { *m = VotesResp{} }
func (m *VotesResp) String() string            { return proto.CompactTextString(m) }
func (*VotesResp) ProtoMessage()               {}
func (*VotesResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *VotesResp) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

// Internal
type VoteRecord struct {
	UUID   string `protobuf:"bytes,1,opt,name=UUID" json:"UUID,omitempty"`
	Source string `protobuf:"bytes,2,opt,name=source" json:"source,omitempty"`
	Target string `protobuf:"bytes,3,opt,name=target" json:"target,omitempty"`
}

func (m *VoteRecord) Reset()                    { *m = VoteRecord{} }
func (m *VoteRecord) String() string            { return proto.CompactTextString(m) }
func (*VoteRecord) ProtoMessage()               {}
func (*VoteRecord) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *VoteRecord) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

func (m *VoteRecord) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *VoteRecord) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func init() {
	proto.RegisterType((*VoteReq)(nil), "ericmoritz.rep.rep.VoteReq")
	proto.RegisterType((*VoteResp)(nil), "ericmoritz.rep.rep.VoteResp")
	proto.RegisterType((*VotesReq)(nil), "ericmoritz.rep.rep.VotesReq")
	proto.RegisterType((*VotesResp)(nil), "ericmoritz.rep.rep.VotesResp")
	proto.RegisterType((*VoteRecord)(nil), "ericmoritz.rep.rep.VoteRecord")
}

func init() { proto.RegisterFile("rpc/rep/service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 293 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x4f, 0x4b, 0x03, 0x31,
	0x10, 0xc5, 0x59, 0xfb, 0x7f, 0xbc, 0x05, 0x95, 0xb2, 0x2a, 0xd6, 0x3d, 0x48, 0x2f, 0x66, 0xa1,
	0x9e, 0x7a, 0x54, 0x7a, 0xf1, 0x26, 0x91, 0x7a, 0x10, 0x2f, 0x6d, 0x1c, 0x6a, 0x0e, 0xdd, 0xc4,
	0x99, 0xac, 0x82, 0x1f, 0xc2, 0xcf, 0x2c, 0x49, 0xd6, 0x7f, 0xc8, 0x7a, 0x48, 0x98, 0xc7, 0xbc,
	0xfc, 0xe6, 0x31, 0x81, 0x7d, 0x72, 0xba, 0x24, 0x74, 0x25, 0x23, 0xbd, 0x18, 0x8d, 0xd2, 0x91,
	0xf5, 0x56, 0x08, 0x24, 0xa3, 0xb7, 0x96, 0x8c, 0x7f, 0x93, 0x84, 0x2e, 0x9c, 0x7c, 0xbe, 0x31,
	0xfe, 0xa9, 0x5e, 0x4b, 0x6d, 0xb7, 0xe5, 0x77, 0xbb, 0xf4, 0xaf, 0x86, 0xdc, 0x79, 0xcd, 0x48,
	0x5c, 0x06, 0x58, 0xaa, 0x7e, 0xe1, 0x8a, 0x07, 0x18, 0xdc, 0x59, 0x8f, 0x0a, 0x9f, 0xc5, 0x1c,
	0x06, 0x8c, 0xcc, 0xc6, 0x56, 0xe3, 0x6c, 0x92, 0x4d, 0x77, 0x67, 0x27, 0xf2, 0xc7, 0xac, 0xf8,
	0xb8, 0xb9, 0x6f, 0x93, 0x4d, 0x7d, 0xfa, 0xc5, 0x01, 0xf4, 0xfd, 0x8a, 0x36, 0xe8, 0xc7, 0x9d,
	0x49, 0x36, 0x1d, 0xa9, 0x46, 0x15, 0x00, 0xc3, 0x44, 0x67, 0x57, 0x9c, 0xa5, 0x9a, 0xc3, 0xa8,
	0x1c, 0x86, 0x81, 0x54, 0xad, 0xb6, 0x18, 0x67, 0x8d, 0xd4, 0x97, 0x2e, 0x4e, 0x61, 0xd4, 0xf8,
	0xd8, 0x89, 0x3d, 0xe8, 0x69, 0x5b, 0x57, 0x3e, 0xba, 0xba, 0x2a, 0x89, 0xe2, 0x06, 0x20, 0x61,
	0xb5, 0xa5, 0x47, 0x21, 0xa0, 0xbb, 0x5c, 0x5e, 0x2f, 0x1a, 0x50, 0xac, 0x43, 0x20, 0xb6, 0x35,
	0x69, 0x1c, 0xef, 0xa4, 0x40, 0x49, 0xb5, 0x05, 0x9d, 0xbd, 0x67, 0xd0, 0x51, 0xe8, 0xc4, 0x25,
	0x74, 0x03, 0x59, 0x1c, 0xca, 0xbf, 0x6b, 0x96, 0xcd, 0xa2, 0xf2, 0xa3, 0xf6, 0x26, 0x3b, 0xb1,
	0x80, 0x5e, 0xcc, 0x2f, 0x5a, 0x6d, 0x61, 0x05, 0xf9, 0xf1, 0x3f, 0x5d, 0x76, 0x57, 0xbd, 0xfb,
	0x0e, 0xa1, 0x5b, 0xf7, 0xe3, 0x2f, 0x5d, 0x7c, 0x04, 0x00, 0x00, 0xff, 0xff, 0xcf, 0xef, 0xa5,
	0xde, 0x0d, 0x02, 0x00, 0x00,
}
